In [4]:
import numpy as np
import pandas as pd
path = "../data/ESX01juin.csv"
df = pd.read_csv(path, delimiter=";")

In [5]:
df.shape

(721, 7)

In [6]:
df.head()

,Time,CPU usage,Used memory,Number of bytes received,Number of bytes transmitted,RLATE,WLATE
0,2019-06-01T00:00:00+02:00,12557883333,"2,27508E+11",13729792,13599351,13,14
1,2019-06-01T01:00:00+02:00,11103150000,"2,27363E+11",10679620,34346939,10,15
2,2019-06-01T02:00:00+02:00,11826533333,"2,27262E+11",9950395,36280285,13,19
3,2019-06-01T03:00:00+02:00,10604033333,"2,27285E+11",6090057,28342289,17,22
4,2019-06-01T04:00:00+02:00,9820616666,"2,27321E+11",2806713,15780899,12,32

In [7]:
df.dtypes

Time                           object
CPU usage                       int64
Used memory                    object
Number of bytes received        int64
Number of bytes transmitted     int64
RLATE                           int64
WLATE                           int64
dtype: object

In [8]:
path2 = "../data/ESX01_2706.csv"
df2 = pd.read_csv(path2, delimiter=";")
df2.head()

,Time,CPU usage,Used memory,Number of bytes received,Number of bytes transmitted,Average read latency of the datastore LUN_080,Average read latency of the datastore LUN_081,Average read latency of the datastore LUN_082,Average read latency of the datastore LUN_083,Average read latency of the datastore LUN_084,Average read latency of the datastore LUN_085,Average write latency of the datastore LUN_080,Average write latency of the datastore LUN_081,Average write latency of the datastore LUN_082,Average write latency of the datastore LUN_083,Average write latency of the datastore LUN_084,Average write latency of the datastore LUN_085
0,2019-06-27T00:00:00+02:00,1.022600e+10,"2,25E+11",5877248.0,31498752.0,1,0,"0,5",0,"1,5",5,1,0,1,0,0,5
1,2019-06-27T00:02:00+02:00,9.362500e+09,"2,25E+11",4866560.0,5431296.0,3,13,"2,5",8,"0,5","22,5",10,"12,5",9,26,8,7
2,2019-06-27T00:04:00+02:00,8.490000e+09,"2,25E+11",5247488.0,5050368.0,4,11,2,12,1,17,5,3,"3,5","0,5",3,5
3,2019-06-27T00:06:00+02:00,9.079000e+09,"2,25E+11",6056960.0,6340608.0,7,"19,5","4,5",6,"2,5",15,"5,5","4,5",8,6,8,"4,5"
4,2019-06-27T00:08:00+02:00,7.504000e+09,"2,25E+11",4986368.0,5183488.0,2,"0,5",2,0,0,"6,5",2,4,3,1,"1,5",3

In [10]:
df2.shape

(720, 17)

In [11]:
df2.dtypes

Time                                               object
CPU usage                                         float64
Used memory                                        object
Number of bytes received                          float64
Number of bytes transmitted                       float64
Average read latency of the datastore LUN_080      object
Average read latency of the datastore LUN_081      object
Average read latency of the datastore LUN_082      object
Average read latency of the datastore LUN_083      object
Average read latency of the datastore LUN_084      object
Average read latency of the datastore LUN_085      object
Average write latency of the datastore LUN_080     object
Average write latency of the datastore LUN_081     object
Average write latency of the datastore LUN_082     object
Average write latency of the datastore LUN_083     object
Average write latency of the datastore LUN_084     object
Average write latency of the datastore LUN_085     object
dtype: object